name: clone appstore json

on:
  workflow_dispatch:
  schedule:
    # 每天 UTC 时间 12:00 运行（北京时间20:00）
    - cron: '0 12 * * *'
    
permissions:
  contents: write  # 允许写入仓库
  
jobs:
  download-and-publish:
    runs-on: ubuntu-latest

    steps:
    # 步骤1：检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 步骤2：下载文件（替换为你的URL和路径）
    - name: Download file
      run: |
        curl -s -o apps.json https://apps.nextcloud.com/api/v1/apps.json
        curl -s -o discover.json https://apps.nextcloud.com/api/v1/discover.json
        curl -s -o categories.json https://apps.nextcloud.com/api/v1/categories.json
        # 或使用 wget：
        # wget -q -O files/data.txt https://example.com/your-file.txt

    # 步骤3：自动提交更改
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Auto-update data file'
        file_pattern: |
          apps.json
          discover.json
          categories.json
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com

