name: clone appstore json

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  download-and-publish:
    runs-on: ubuntu-latest

    steps:
    # 步骤1：检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 步骤2：下载文件（替换为你的URL和路径）
    - name: Download file
      run: |
        curl -s -o apps.json https://apps.nextcloud.com/api/v1/apps.json
        # 或使用 wget：
        # wget -q -O files/data.txt https://example.com/your-file.txt

    # 步骤3：自动提交更改
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Auto-update data file'
        file_pattern: apps.json  # 监控指定文件变化
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com

