name: clone appstore json

on:
  workflow_dispatch:
  schedule:
    # 每天 UTC 时间 12:00 运行（北京时间20:00）
    - cron: '0 12 * * *'
    
permissions:
  contents: write  # 允许写入仓库
  
jobs:
  download-and-publish:
    runs-on: ubuntu-latest

    steps:
    # 步骤1：检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 步骤2：下载文件（替换为你的URL和路径）
    - name: Download file
      run: |
        wget -q -O apps.json https://apps.nextcloud.com/api/v1/apps.json
        wget -q -O discover.json https://apps.nextcloud.com/api/v1/discover.json
        wget -q -O categories.json https://apps.nextcloud.com/api/v1/categories.json
        wget -q -O appapi_apps.json https://apps.nextcloud.com/api/v1/appapi_apps.json
        # 或使用 wget：
        # wget -q -O files/data.txt https://example.com/your-file.txt
   
    # 步骤3：使用github镜像源加速应用下载链接
    - name: Replace github.com with github mirror in the JSON file
      run: |
        sed -i 's|github\.com|v6.gh-proxy.org/https://github.com|g' apps.json
        sed -i 's|github\.com|v6.gh-proxy.org/https://github.com|g' discover.json
        sed -i 's|github\.com|v6.gh-proxy.org/https://github.com|g' appapi_apps.json
        
    # 步骤4：自动提交更改
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Auto-update data file'
        file_pattern: categories.json discover.json apps.json
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com

